version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = [
    "api/**",
    "proto/**",
    "schema/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/temporalio/temporal"]
